[project]
name = "plantrnafm-preprocessing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.9.0",
    "polars>=1.33.1",
    "pyarrow>=16.1.0",
    "pyfastx>=2.3.2",
    "ruff>=0.6.2",
]
