
name: Build and Push Singularity Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    matrix:
        singularity_version:
          - '3.10.3'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Container
        run: |
          sudo -E singularity build plantrnafm_preprocessing.sif Singularity.def

      - name: Push Singularity image to GHCR
        run: |         
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest
